pipeline {
    agent any
    stages{
        stage("clone ansible playbook") {
            steps {
                git credentialsId: '5fbf29ca-18b1-462c-87c8-ec8f88a4788e', url: 'https://github.com/lolspider/ansible-shop.git'
            }
        }
        stage("run playbook to deploy project and check it") {
            steps {
		withCredentials([file(credentialsId: 'git-crypt', variable: 'git_crypt')]) {
                    sh 'git-crypt unlock "$git_crypt"'
                    sh "sudo chmod 600 ssh_keys/*"
                    sh "ansible-playbook -i $inventory --extra-vars 'BUILD_ID=${env.BUILD_ID}' -u vagrant -b $playbook"
                }
            }
        }
    }
}
